set_false_path -from [get_ports hps_io_hps_io_sdio_inst_CMD] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_sdio_inst_CMD]
set_false_path -from [get_ports hps_io_hps_io_sdio_inst_D0] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_sdio_inst_D0]
set_false_path -from [get_ports hps_io_hps_io_sdio_inst_D1] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_sdio_inst_D1]
set_false_path -from * -to [get_ports hps_io_hps_io_sdio_inst_CLK]
set_false_path -from [get_ports hps_io_hps_io_sdio_inst_D2] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_sdio_inst_D2]
set_false_path -from [get_ports hps_io_hps_io_sdio_inst_D3] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_sdio_inst_D3]
set_false_path -from [get_ports hps_io_hps_io_gpio_inst_LOANIO49] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_gpio_inst_LOANIO49]
set_false_path -from [get_ports hps_io_hps_io_gpio_inst_LOANIO50] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_gpio_inst_LOANIO50]
set_false_path -from [get_ports hps_io_hps_io_gpio_inst_LOANIO55] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_gpio_inst_LOANIO55]
set_false_path -from [get_ports hps_io_hps_io_gpio_inst_LOANIO56] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_gpio_inst_LOANIO56]